= ArwynFr.SemanticVersion

A powershell module used to increment semantic version numbers.

https://www.powershellgallery.com/packages/ArwynFr.SemanticVersion[image:https://img.shields.io/powershellgallery/v/ArwynFr.SemanticVersion?style=for-the-badge[PowerShell Gallery]] https://www.powershellgallery.com/packages/ArwynFr.SemanticVersion[image:https://img.shields.io/powershellgallery/dt/ArwynFr.SemanticVersion?style=for-the-badge[PowerShell Gallery]] link:/LICENSE[image:https://img.shields.io/github/license/ArwynFr/pwsh-SemanticVersion?style=for-the-badge[GitHub License]]

You can download and install this powershell module from PSGallery:

```Powershell
Install-Module ArwynFr.SemanticVersion
```

== ConvertTo-SemanticVersionBump

This function returns `major`, `minor` or `patch` depending on the presence of a `+semver: major` or `+semver: minor` tag in the commit message. It is intended to be used with `Step-SemanticVersion`.

```Powershell
ConvertTo-SemanticVersionBump
  [[-CommitMessage] <string>]
  [<CommonParameters>]
```

`-CommitMessage`:: *Required* and *Pipelinable*. A commit message string that the command will use as an input.

== Step-SemanticVersion

Returns an incremented semantic version number.

```Powershell
Step-SemanticVersion
  [[-Version] <semver>]
  [-BumpType] {major | minor | patch}
  [[-PreRelease] <string>]
  [[-Build] <string>]
  [<CommonParameters>]
```

`-Version`:: *Required* and *Pipelinable*. Current version from which to do the increment.

`-BumpType`:: *Required*. Must be one of `major`, `minor`, or `patch`. The new version number is incremented based on this value.

`-PreRelease`:: *Optional*. If specified, sets the pre-release value of the new version.

`-Build`:: *Optional*. If specified, sets the build value of the new version.

== New-GithubSemanticVersionRelease

This function creates a new GitHub release by getting the latest release version and incrementing based on the presence of a `+semver: major` or `+semver: minor` tag in the current commit message. 

```Powershell
New-GithubSemanticVersionRelease
  [-AddTags]
  [<CommonParameters>]
```

`-AddTags`:: *Optional* switch. If set, the command will also create and force push tags for major and minor versions.