= StepSemVer

StepSemVer is a pwsh module used to increment semantic versions number.

https://www.powershellgallery.com/packages/StepSemVer[image:https://img.shields.io/powershellgallery/v/StepSemVer?style=for-the-badge[PowerShell Gallery]] https://www.powershellgallery.com/packages/StepSemVer[image:https://img.shields.io/powershellgallery/dt/StepSemVer?style=for-the-badge[PowerShell Gallery]]

== Rules and standards

The following documents provide additional information on rules and standards applying to this project :

- link:/LICENSE[MIT License]

== Installing

You can download and install this powershell module from PSGallery:

```Powershell
Install-Module StepSemVer
```

== Usage

=== ConvertTo-SemanticVersionBump

This function returns `major`,  `minor` or `patch` depending on the presence of a `+semver: major` or `+semver: minor` tag in the commit message. It is intended to be used with `Step-SemanticVersion`.

```Powershell
ConvertTo-SemanticVersionBump
  [[-CommitMessage] <string>]
  [<CommonParameters>]
```

`-CommitMessage`:: *Required* and *Pipelinable*. A commit message string that the command will use as an input.

=== Step-SemanticVersion

Returns an incremented semantic version number.

```Powershell
Step-SemanticVersion
  [[-Version] <semver>]
  [-BumpType] {major | minor | patch}
  [[-PreRelease] <string>]
  [[-Build] <string>]
  [<CommonParameters>]
```

`-Version`:: *Required* and *Pipelinable*. Current version from which to do the increment.

`-BumpType`:: *Required*. Must be one of `major`, `minor`, or `patch`. The new version number is incremented based on this value.

`-PreRelease`:: *Optional*. If specified, sets the pre-release value of the new version.

`-Build`:: *Optional*. If specified, sets the build value of the new version.
